version: '3'

services:
  db:
    container_name: cooltura_db
    env_file: ./backend/src/.env
    image: postgres
    restart: always
    volumes:
      - "cooltura_db_volume:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  backend:
    container_name: cooltura_backend
    env_file: ./backend/src/.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "2080:2080"
    depends_on:
      - db
    volumes:
      - ./backend/src/:/src


  frontend:
    container_name: cooltura_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  cooltura_db_volume:
