version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "node:14.18.1-alpine3.14"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "node:14.18.1-alpine3.14"
    ports:
      - "3000:3000"
    links:
      - "backend:be"

